version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  stripe_adapter:
    restart: on-failure
    build: ./stripe_adapter
    ports:
      - '8082:8082'
  backend:
    restart: on-failure
    build: ./backend
    ports:
      - '8080:8080'
  admin:
    restart: on-failure
    build: ./frontend-admin
    ports:
      - '5173:5173'
  mvp:
    restart: on-failure
    build: ./frontend-admin-mvp
    ports:
      - '5174:5173'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./backend/data:/var/lib/postgresql/data
volumes:
  db:
    driver: local